name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar Repo A (tu código)
      - name: Checkout Repo A
        uses: actions/checkout@v3

      # 2️⃣ Configurar Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Construir y subir la imagen
      - name: Build and Push Docker Image
        run: |
          chmod +x ./build-and-push.sh
          ./build-and-push.sh

      # 4️⃣ Generar el tag de la imagen
      - name: Set image tag
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # 5️⃣ Actualizar Helm Chart en Repo B
      - name: Update Helm Chart in Repo B
        run: |
          # Clonar Repo B en un directorio temporal
          git clone https://github.com/jreb-123/.ks8-final-project repo-b
          cd repo-b

          # Modificar el archivo values.yaml con el nuevo tag
          sed -i "s/tag:.*/tag: $TAG/" charts/mini-stack/values.yaml

          # Hacer commit y push
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add charts/mini-stack/values.yaml
          git commit -m "Update image tag to $TAG"
          git push https://$GITHUB_TOKEN@github.com/jreb-123/.ks8-final-project main
